name: Develop Workflow
# This workflow is triggered on pull requests to the develop branch only.
on: 
  pull_request: 
    branches: 
      - develop
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   
    - name: Cache node modules
      uses: actions/cache@preview
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      
  build: 
    runs-on: ubuntu-latest
    needs: [install]
    steps: 
      - uses: actions/checkout@v1
      
      - name: Cache node modules
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Alpha Package
        run: npm run build   
