name: Develop Workflow
# This workflow is triggered on pull requests to the develop branch only.
on: 
  pull_request: 
    branches: 
      - develop
jobs:
  install:
    name : ✨Install Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   
    - name: Cache node modules
      uses: actions/cache@preview
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
     
    - name: Install Packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      
  build: 
    name : 🛠 Build Affected
    runs-on: ubuntu-latest
    needs: [install]
    steps: 
      - uses: actions/checkout@v1
      
      - name: Cache node modules
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 🛠 Build Alpha Package
        run: npm run affected:build -- --base=origin/develop --head=HEAD
      
      - name: Archive Build - Artifacts
        uses: actions/upload-artifact@master
        with:
          name: build
          # only one application for demo
          path: dist
     
  ts-lint-affected: 
    name : ✅ Lint - TypeScript
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v1
      
      - name: Cache node modules
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ✅ Lint - TypeScript
        run: npm run affected:lint -- --base=origin/develop --head=HEAD

  unit-test-affected: 
    name: 🧪 Unit Tests Affected
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v1
      
      - name: Cache node modules
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 🧪 Unit Tests Affected
        run: npm run affected:test -- --base=origin/develop --head=HEAD
  e2e-affected: 
    name: 🦄 E2E Affected
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: actions/checkout@v1
      
      - name: Cache node modules
        uses: actions/cache@preview
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name : Install Cypress
        run: npm run cypress-install
      - name: 🦄 E2E Affected
        run: npm run affected:e2e  -- --base=origin/develop --head=HEAD
 