name: Develop Workflow
# This workflow is triggered on pull requests to the develop branch only.
on: 
  pull_request: 
    branches: 
      - develop
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: npm ci
  build: 
    runs-on: ubuntu-latest
    needs: [install]
    steps:
          - name: Build Alpha Package
            run: npm run build    
